language: python
python:
  - 3.5
sudo: required
# services:
#   - docker
# before_install:
#   - docker run --name postgres -e POSTGRES_PASSWORD=test -d postgres
install:
  - pip install -U pip
  - pip install tox
script:
  - ./scripts/sbtassembly
  - tox
